export default [
  {
    title: 'Budapest',
    slug: 'budapest',
    postDate: '',
    body: `
      We kicked off our visit to Budapest with a couple of back to back history museum visits. Man, the 20th century history of Hungary is bleak. Nevertheless, it didn't mar our enjoyment of Budapest's many coffee and cake stops. Of all the influences that have poured into the city over the centuries, the persistent cloud cover brought out the Soviet patina. I'm into it.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/main.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/river.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/boat.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/parl-5.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/parl-1.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/parl-2.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/parl-3.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/parl-4.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/parl-6.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/glow.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/soldiers.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/grunge.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/czendes.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/graff.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/door.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/keleti.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/memento-1.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/memento-2.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/statue.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/subway.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/syna.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/cafe.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/antiq.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/zoo-1.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/zoo-2.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/budapest/zoo-3.jpg',
    ],
  },
  {
    title: 'Edinburgh',
    slug: 'edinburgh',
    postDate: '',
    body: `
      It seems like an eternity since we got back from the North American tour. That makes sense really, given that that trip bottomed out our bank accounts for pretty much a year. Getting back to it though, we had a really relaxed trip to Edinburgh for Hogmanay. It's a beautiful city, and for whatever reason I can't help but drastically exaggerate my Scottish ancestry while I'm there.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/skyline-dim.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/skyline-castles.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/william-st.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/william-st-christmas.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/royal-alley.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/st-giles.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/holyrood.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/leigh.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/ferris-wheel.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/stage-waiting.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/stage-wet.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/stage-drunk.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/firework-bokeh.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/firework-red.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/firework-multi.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/arthur-hill.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/arthur-trails.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/sunset-stand.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/edinburgh/sunset.jpg',
    ],
  },
  {
    title: 'Washington D.C.',
    slug: 'washington-dc',
    postDate: '',
    body: `
      When we booked the trip, it didn’t occur to me — the significance of coming to the nation’s capital for our final stop. The capital was a good place to reflect back on all our stops over the past few weeks. It feels apart from the diverse country we just travelled all over. Yet, it contains the foci of pretty much every institution, every historical thread, every agency, every major national incident in the United States. There’s a museum for everything.

      In Washington, with its meticulous and deeply metaphorically loaded city grid, its acres of methodically planned parks and malls, you are never more aware of the deliberate architecture of the country. Is that a good representation of the country as a whole? Definitely not. However, it’s the best place to understand the idea behind this gigantic maelstrom of a country. I’m glad I got to get amongst it. I look forward to coming back and seeing a little more.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/washington-monument-crowd.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/andrew-jackson-statue.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/woodrow-wilson-chair.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/lincoln-memorial.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/white-house-north.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/white-house-south.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/washington-monument-cherry.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/mlk-washington.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/jefferson-pedalo.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/cherry-crowd.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/capitol-inner-dome.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/capitol-outer-dome.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/adams-morgan.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/arlington-stripes.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/compton-arlington.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/dc-central.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/lizzie-fishtank.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/washington-dc/newseum.jpg',
    ],
  },
  {
    title: 'Boston',
    slug: 'boston',
    postDate: '',
    body: `
      More than the other cities we’ve been to, Boston felt like a place steeped in history. Nowhere more than here did you feel like the hard-won independence of the country was something worth applauding. Sure, we Europeans chuckle under our breath when excitable tour guides tell us how ancient this or that building from the 18th century is, but part of what makes the place impressive is what the country has managed to become in such a short space of time.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/boston-statehouse.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/franklin-grave.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/old-state-house.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/revere.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/revere-steeple.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/lunch-lady.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/charles-runners.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/charles-drinks.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/harvard-yard.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/harvard-comp-sci.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/harvard-electric.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/cambridge-bookstore.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/jp-steps.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/jp-night-lizzie.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/boston-pl.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/boston/boston-governor.jpg',
    ],
  },
  {
    title: 'New York City',
    slug: 'new-york-city',
    postDate: '',
    body: `
      It seems almost inappropriate to put all of these photos in one post. The places we covered in the city are so different, and there’s so many different subjects in the photos below that they could be from a dozen different cities — but they’re not. They’re all from one crazy, smelly, stunning, exhausting city. Oh, and we didn’t even go to Brooklyn.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/rock-view.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/projects.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/downtown.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/upper-west-side.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/bk-bridge.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/copper-top.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/met-artemis.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/met-palace.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/sputnik.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/security-council.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/subway-tude.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/rock-view.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/pavement-bright.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/nypd.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/oculus.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/new-york-city/liberty-head.jpg',
    ],
  },
  {
    title: 'Toronto',
    slug: 'toronto',
    postDate: '',
    body: `
      I feel like we probably didn’t do Toronto justice. It’s our halfway point, and we’ve got three amazing cities coming up — with a week in each. We want to have as much energy as we possibly can to throw into discovering them, and we want to be caught up on rest from the streak of short stops we just had. So yeah, we ordered some takeout and yeah, we didn’t explore outside of our own neighbourhood that much. But you know what, we ate some amazing food and we watched a whole season of House of Cards — so there.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/airport-view.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/graffiti.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/qs-cables.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/cn-cables.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/street-reader.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/niagara-wide.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/cold-falls.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/falls-city.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/niagara-river.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/s-bend.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/pizza.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/cn-scape.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/rbc-scape.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/sim-city.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/rail-yard.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/toronto/floor-selfie.jpg',
    ],
  },
  {
    title: 'Chicago',
    slug: 'chicago',
    postDate: '',
    body: `
      From across Lake Michigan (it’s a sea though, isn’t it? - let’s not kid ourselves), Chicago looks a frigid, imposing grid. You can see where the excess of ironwork from America’s past has stuck around and been forged into buildings that look as cold as the ground around them. At street level though, it’s a totally different beast. It’s basically New York City’s quieter, diminutive sibling. The architecture here is some of the best I’ve ever seen, and despite the numerous warnings we’d been getting about the cold — I found it pretty hospitable.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/aerial-burbs.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/aerial-cold.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/aerial-red.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/north-side.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/bnb-shelves.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/bnb-kitchen.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/bnb-bathroom.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/starbucks.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/maroc.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/arches.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/cold-scrape.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/tribune.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/dock.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/sears-cold.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/inst-degas.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/flamingos.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/sand-cat.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/snow-panda.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/chicago/snow-monk.jpg',
    ],
  },
  {
    title: 'San Francisco',
    slug: 'san-francisco',
    postDate: '',
    body: `
      I feel bad for Chicago, because I’m not very happy to be flying there from this city right now. I love this city so much, for so many reasons. This time around, I’ve managed to see so many more neighbourhoods and soak them in. From the Mission, to Castro, to North Beach, to the Marina — they are all so distinct and so alive.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/dusk-bay.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/mission-roses.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/mission-church.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/mission-park.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/castro-parrot.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/presc-lizzie.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/presc-balcony.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/palace.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/russian-hill.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/tram.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/whole-foods.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/coit-trees.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/coit-church.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/chinatown-cables.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/japantown.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bay-wave.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bridge-bw.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bridge-forest.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bridge-beach.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bay-beach.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/alcatraz-light.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/alcatraz-tour.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bay-alcatraz.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bay-dark.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/bay-dark-colour.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/balboa.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/downtown-dusk.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/san-francisco/twin-peaks.jpg',
    ],
  },
  {
    title: 'Yosemite',
    slug: 'yosemite',
    postDate: '',
    body: `
      National Parks might be the best idea the United States has ever had. Some super old, super dead white guys managed to convince President Lincoln (who probably thought he had way more pressing matters at hand) to sign the Yosemite Grant in 1864. Since then the scope of preservation, not just of Yosemite but of the model for all National Parks, has expanded massively. Now there’s these incredible swathes of land, total wilderness really, guarded by the big, scary federal government — so don’t drop your goddamn Starbucks on the ground. I like it.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/valley-wide.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/falls-distant.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/forest.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/falls-forest.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/falls-bw.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/rock-relief.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/yosemite/half-dome-forest.jpg',
    ],
  },
  {
    title: 'Los Angeles',
    slug: 'los-angeles',
    postDate: '',
    body: `
      You know the TV depictions of the Southern Californian bubblehead? It’s not a gross exaggeration. It took me until I was sat in a shopping mall in Hollywood to hear my first, but sure enough along came a woman with overlarge sunglasses, a Starbucks in one hand, and her iPhone and dog leash (attached to a just-barely-visible-to-the-naked-eye Chihuahua) in the other. She was complaining loudly about how Chet stood her up, but she thought the thing was sketchy anyway because who tries to plan a date at a taqueria?
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/highway-strip.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/hot-palms.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/hot-skyline.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/in-out.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/in-out-ext.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/starbucks-guy.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/capitol-recs.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/bnb.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/hollywood.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/wb-tower.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/wb-escapes.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/wb-signs.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/wb-hills.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/wb-theatre.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-hut.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-paddle.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-bw.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-beard.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-skin.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-surf.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-sunset.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/los-angeles/sm-lap.jpg',
    ],
  },
  {
    title: 'Las Vegas',
    slug: 'las vegas',
    postDate: '',
    body: `
      These past few days, I’ve just been finding myself saying “This doesn’t make any sense” over and over again. The scale of these hotel resorts makes no sense, the desert in the background of this golf course makes no sense. It goes on and on, the contradiction of this place. It’s a hell of thing to behold, though.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/strip-mgm.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/desert-airport.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/desert-jet.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/desert-ads.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/desert-strata.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-caesar.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-flamingo.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-gold.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-harrah.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-mirage.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-paris.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/casino-mirage-ceiling.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/pink-doors.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/sky-tower.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/strip-stores.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/strip-night-road.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/las-vegas/strip-construction.jpg',
    ],
  },
  {
    title: 'Grand Canyon',
    slug: 'grand canyon',
    postDate: '',
    body: `
      It took a fair bit of convincing for me to be on board with starting the trip out in Las Vegas. A big part of the argument for Vegas was the opportunity to visit the Grand Canyon, which I’ve been vastly underestimating until today.
    `,
    photos: [
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-wide-bw.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-winch.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-bw.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-red.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-peek.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-relief.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-hut.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/desert-flat.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/joshua-lump.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/joshua-close.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/joshua-s.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/joshua-peak.jpg',
      'https://s3.eu-west-2.amazonaws.com/jackwreid/jackwreid/trips/grand-canyon/canyon-panorama.jpg',
    ],
  },
];
