import React from 'react';

import WritingArticle from '../../components/WritingArticle';

export default () => (
  <WritingArticle
    title="Twitter's Desktop Troubles"
    subtitle="Changes To Twitter’s Desktop Experience That Could Make All The Difference"
    slug="twitters-desktop-troubles"
    date="29th June 2015">
    <p>Twitter’s been getting second guessed a lot recently. They’ve had their whole business model <a href="https://medium.com/@sacca/what-twitter-can-be-986a42419f8">re-appraised by Chris Sacca</a>, and off the back of that, a lot of design brains have been making suggestions on the visual side of things. I’d feel sorry for the people working at Twitter if, well, if they didn’t get to work at Twitter for their job. There’s a reason Twitter as a product and a platform is worth all this lip service: it’s fucking amazing.</p>
    <p>I don’t need to go through the reasons why Twitter got to where it is today. What I want to do is talk about the features whose worth Twitter doesn’t seem to have fully realised yet. A lot of Twitter’s enormous potential is getting suppressed by missed opportunities and odd design choices, especially when it comes to the desktop web experience. I use TweetDeck for the browser as my desktop portal into the medium a lot these days, and it’s because it unleashes a lot of the potential that the platform has.</p>
    <p>Twitter for desktop should allow power users of the service to flex their muscles. The mobile experience has been really optimised for casual scrolling, tweeting, and faving. However, the added screen real estate and full tactile keyboard that you can take for granted when designing a desktop experience is really going to waste with Twitter. Not everybody will use these additional features (which are really just better exposure of existing services), but the desktop is the place to tastefully integrate advanced features without alienating more casual users. Below are my suggestions to convince me to come back to twitter.com.</p>
    <h2>Multiple Account Support</h2>
    <p>This seems totally crazy but right now Twitter for the web has no support for multiple accounts. The mobile application, on the other hand, has a really accomplished implementation of multiple accounts. TweetDeck has a pretty great implementation of multiple account, as do many third-party applications. So the question remains, why the hell hasn’t twitter.com integrated a kick-ass multiple accounts implementation?</p>
    <p>I refuse to believe that there isn’t a market for being able to frequently flip between two or more accounts. From my own experience, I know plenty of people who have more than one Twitter account. I have one for general news and my friends, and another that I use for design and development, so I don’t have to subject my friends to code-talk. A lot of people around my age group manage the social networks of companies they’re getting their first jobs at, intern style. A friend of mine has a second Twitter account so he can talk about football on it without pissing off his friends who don’t care about football.</p>
    <p>So, what’s the implementation to be? Well it shouldn’t be too hard, just like it isn’t in the mobile app. Just integrate a profile switcher into the dropdown from the profile picture. The option is so conventional that it seems odd that it isn’t already there. To help distinguish between the multiple accounts, each one could contain a small profile picture. In fact, I occasionally click on the profile picture, forgetting that the feature isn’t already there. While we’re in that dropdown, get rid of lists (we’ll come back to lists in a minute), get rid of keyboard shortcuts and integrate it into the help section.</p>
    <img src="http://jackwreid.uk/writing/twitters-desktop-troubles/photos/profiles.png" alt="Profiles" />
    <p>There is the question of technical implementation. I’m aware that it is somewhat easier to have multiple accounts on a native application, such as the iOS app. In those cases, you have an endpoint that lives on the offline software, and is logged into multiple accounts. In a browser, you don’t have that kind of storage and it’s a different paradigm to develop for. However, take the way Google handles accounts. I don’t even know how Google does it, but when I go to switch Google accounts, it has a list of previous accounts I’ve logged into for me to quick switch to. I believe in you Twitter, you can solve this.</p>
    <h2>Bring Lists To The Fore</h2>
    <p>Lists are perhaps the most drastically underdeveloped feature of Twitter. They have the potential to utterly transform the platform into something much, much more powerful. I currently use Twitter lists in TweetDeck to split out my dashboard into the firehose feed on the left, a feed of my friends second, a feed of technology and development news third, a feed of notifications fourth, and finally, a stream of my own tweets. This set up wouldn’t be possible if it weren’t for the core feature of lists in Twitter.</p>
    <p>Lists are simultaneously two things: lists of users and streams of those users’ tweets. I think the former has been overplayed thus far, and the latter really undersold. Bear with me for a moment and regard the lists features as just streams of content.  There’s a rise in bundling content by topical category, just look at Google’s Inbox and its bundles feature. The same should go for lists in Twitter. Switch out the tweet box at the top of the stream (it could easily go where the trending topics box is on the left column), and replace it with a tabbed stream selector. Now the user has far easier access to their lists, which they are more encouraged to curate, and which are manifested more as streams than collections of accounts.</p>
    <img src="http://jackwreid.uk/writing/twitters-desktop-troubles/photos/streams.png" alt="profile" />
    <p>Once you’ve re-imagined lists as prominent streams of content with access right at the top of the interface, you can go a long way with them. The timeline as we know it is the first stream, then you can arrange your own lists as streams on that row of tabs. Another tab that Twitter would themselves curate would be the trending tab, which would group prominent tweets from trending topics (regardless of whether you follow the users who tweeted them). Twitter could also add temporary streams for huge news stories, for example a stream of all tweets about a terror attack, pinned as a tab. The same goes for promotions, for example any given hashtag could be pinned as a stream tab.</p>
    <h2>Overhaul The Third Column</h2>
    <p>The third column of the Twitter desktop experience seems to be a sort of leftover. Sure, user research tells us that the right side of the page is the least trafficked by the eye (at least amongst left-to-right readers). However, the right column is really being wasted. The largest module, the ‘Who to follow’ box, could be removed with my suggestions as the Twitter-supplied streams at the top of the timeline would introduce myriad users outside of the reader’s following list to their attention.</p>
    <p>So all that remains there is that catch-all box of links to rarely trafficked parts of the site. Nearly a third of the window width devoted to something that really belongs as an insignificant footer? It seems like a huge waste of real estate. This column should either be removed for the sake of a little more whitespace, or replaced with a notifications stream. Notifications, after the timeline, are my most trafficked area of the website as it currently stands. Either way would be a drastic improvement over the seemingly pointless inclusion of the current contents of the right column.</p>
    <h2>Sort Out The New Tweets Indicator</h2>
    <p>The way twitter.com deals with the constantly flowing stream of new tweets in the active stream is just wrong, in my opinion. Firstly, the title tag of the page should not show the number of unread tweets in the browser’s tab or window. Elsewhere on the web, it seems to me that we have agreed that notifications manifested in the title tag require immediate attention - or at least represent the primary unit in a messaging service like email or instant message. It is not, therefore, suitable to use it to represent unread tweets. The number in the tab becomes meaningless when representing tweets because no user has the intention of reading every single tweet referred to in the notification number. In short, don’t put notifications about timeline tweets in the title tag.</p>
  </WritingArticle>
);
