import React from 'react';

import WritingArticle from '../../components/WritingArticle';

export default () => (
  <WritingArticle
    title="The Jetset Ape"
    subtitle="Would We Be Happier Sitting Still?"
    slug="the-jetset-ape"
    date="8th April 2016">
    <p >The benefits of in depth local knowledge have been done to death. Every large consumer-facing company makes a particular effort to claim that no matter how large they are, your local outlet or branch will feel local. It harkens back to what is perhaps a romanticised notion of how it used to be, when you knew your local grocer and they would have your regular order ready, or whatever. The notion can come of as a bit dubious sometimes. I sometimes see it as an evolution of the noble savage fallacy: the idea that those who exist outside of ‘civilisation’ have a spirituality and a vitality that we in our over-connected world cannot attain.</p>
    <p>I’ve been thinking about this idea a lot recently because of how much I’ve been travelling. I just got back from six weeks city-hopping in North America, and like any person who does a period of travel like that, I feel like my general understanding of the world has improved a little. I feel like newly inspired by what I’ve seen, my concern and motivation to address certain global issues has been invigorated by seeing their effects first hand. You know, young white saviour abroad stuff.</p>
    <p>Now I’m home. I’m living in rural England; the pace of life is slower, there is just less going on. During my adjustment period, I’ve been thinking about how to appreciate where I am. Isn’t it better to know one place really well than to touch and go all over the world? I’ve been reading a book called Happy City, which decries what the sprawling suburb has done to the populace’s psyche. One of the major problems with modern living is that people feel disconnected from where they live because they travel from their island in the suburbs right to where they work, and back within the day. They don’t know their immediate surroundings because they’re never out there on foot checking them, and they end up feeling isolated in their own homes.</p>
    <p>Are these people any more exposed to the world because they work far from home? Would they be better off working and living in the same two or three mile radius for their entire lives? Whilst trying to avoid the noble savage fallacy, I imagine somebody who lives and works on a family farm. They know every creek and crevice on the land around them, they feel intimately the season’s changes as they sweep across the landscape. They are, put simply, intimately connected to their environment.</p>
    <p>In a reality where we can fly from city to city with ease and breathe in the local culture for a week or so before moving on, I wonder if we’re actually capable of feeling the full benefit of an environment’s richness. We have taken our ape intelligence and stretched it thin over geographically disparate, high-speed connections, be they highways, flight paths, or fibre-optic cables. We expect ourselves to adapt from the African plains hunter who used its intelligence to know its environment closely to outsmart prey that was far faster than itself. Maybe our minds are elastic enough to be at ease knowing a little about a lot, or maybe we’re missing out by shutting out the slow life, in which you would be predict the weather just by looking at the grass.</p>
    <p>P.S. Thinking about this, I note that HSBC: a global organisation claiming it could optimise the local at each and every outlet, has gotten rid of its ‘The World’s Local Bank’ slogan. Perhaps they realise that even a company of their size cannot exist so broadly, and so deeply as they claimed.</p>
  </WritingArticle>
);
