import React from 'react';

import WritingArticle from '../../components/WritingArticle';

export default () => (
  <WritingArticle
    title="Depop Does Day 4"
    subtitle="Everybody at Depop should talk to users"
    slug="depop-day4"
    date="26th October 2016">
    <p>That first week after somebody decides to install Depop is really important to us. How do we take someone from being casually curious about the app to totally hooked? How do we make a new user feel totally at home in an established, tight-knit community? These are things we think about a lot, of course, and much of the work we do at Depop on a day-to-day basis is helping new users over this threshold. In this article, I’m going to explore our unique solution to this problem, speaking to a few people around the company and getting their perspectives on the way that we reach out to our users during the most crucial time of their user journey.</p>
    <p>Spoiler alert: Depop Does Day 4 (DDD4) is our solution. Four days after creating an account, new users get a private in-app message from a Depop employee from one of our three offices. These messages arrive in the user’s inbox like any normal message from any other Depop user. There’s no special UI to declare that somebody has descended from on high to shake the new user’s hand; just a message from another user of the app — a user who also happens to work at Depop. Each of these messages come from a staff member who has signed up for the DDD4 scheme.</p>
    <p>The ask for employees who choose to participate is this: give us your Depop username, some of your time, and a few variations of a welcome message you’d like to have sent out to new users. Every single new user receives one of these welcome messages on their fourth day of having the app; the load divided across all DDD4 participants. Which welcome message the user receives depends on where they are in their user journey — we send one kind of message if the user hasn’t made a sale or purchase yet, meaning they haven’t gotten sucked into the app yet and might need some guidance, and a few other variations depending on if they’ve started buying or selling. We want to meet the users wherever they are on day four, and take them to a more successful place. If and when the user replies, we get a message in-app and continue the conversation, just like any other interaction on Depop.</p>
    <p>It’s really important to us that every employee writes their own unique messages. David, a product manager at Depop, emphasises that aspect: “Getting a personalised message addressed to you, that opens a personal communication channel with someone.”</p>
    <p>What’s more, opening the tone of the conversation as we would any other personal conversation reminds the user that they’re talking to just that — a real person. There’s no barrier between us and the user; we can totally be ourselves. After all, what is the tone of Depop if not that our voices collectively? Meg Rowland is our editorial manager in the New York office who has a particular focus on establishing Depop’s tone. She notes that we don’t give DDD4 participants any coaching, and that’s because we don’t want to sound like robots. Sure it can be a little intimidating the first time a user comes to you needing help, but before long you realise you’re just a person with some information helping another person with a little less information.</p>
    <p>Once a user has been sent their first DDD4 message, they have a personal point-of-contact with a real Depop staff member. When you stop and think about that for a moment, that’s pretty incredible. Every single user who joined Depop after we starting doing this in early 2015 has a personal contact on the Depop staff. Something that came up in my conversations with Depop staff was how we think this helps make our users feel special. That’s not to say we think of ourselves as anything special, but I think that as a new user of any product, it feels pretty great to be contacted by the creators. It makes you feel like the product is going to be formed in some way, however small, by your needs.</p>
    <p>So, we have staff members all over the company, all over the world, talking to users all day, also all over the world. In a lot of these cases, though, these conversations don’t stop on day four — they carry on throughout the user’s lifetime on Depop. These relationships become an invaluable tool to our Product team, who make decisions on behalf of the user every day. We hate making assumptions before we make product decisions (also why we have data analysts embedded in our teams), so it’s a blessing that so many of us have this user empathy superpower. If we’re not sure if a user would benefit from a proposed product change, we can just go and ask one. They’re right there in our inboxes! Meg conveys the importance of this check really well: “Without that connection, you risk becoming too focused on the product and forgetting about what your user wants. DDD4 is one of the best sources of user feedback we have in the company.”</p>
    <p>Now it’s time to talk about a gnarly business word: engagement. In the first trials of the DDD4 scheme back in 2015, we found that users who had been contacted by Depop engaged with the app up to 50% more than those who weren’t contacted. We measured that engagement over the subsequent days and found that that yes, the pattern held: users who got contacted stayed more engaged in the long-run and were less likely to abandon Depop.</p>
    <p>And now onto another gnarly business word: scale. How do we make sure that we reach out to every single new user without snowing our staff under with an impossible number of conversations to keep up with? There’s a couple of routes we could take. Do we automate to some extent? How do we do that without losing what makes DDD4 so great in the first place, the real human touch? A couple of our power-DDD4ers like Delia, a community growth manager in our London HQ, are already resorting to expanding text snippets to answer FAQs, just to keep up with the volume whilst providing our users with valuable help.</p>
    <p>Our conversations with users happen exclusively within the Depop messaging system, which is great for dogfooding enthusiasts, however, as our platform expands to the web, a lot of us DDD4ers can’t wait until we can have a desktop browser messaging experience to really deal with conversations at volume. The same goes goes for power-sellers who are talking to dozens of buyers at a time, by the way. (We know that partially because of DDD4 conversations.)</p>
    <p>Speaking of power-sellers, another thing we’re trying out and hoping to expand on is reaching out to those users just crossing over into major-seller territory and coaching them to reach the next level. Delia and Lilli in the community team have started reaching out to users with high-selling potential, simply by initiating a conversation about what we could be doing better for people who are probably starting to make serious money on Depop. This is definitely something we’d like to build more around. There’s a lot of improvements we’d already like to make to the app that are made even more important by our needs as DDD4ers, and that’s great.</p>
    <p>We’re really proud of this stuff, but there’s plenty more to work on to make sure that we’re always understanding our users as best we can. Let us know if you have any thoughts on the way we do this.</p>
    <p>–</p>
    <p>Special thanks to Sam, Meg, Delia, Bex, David, Lauren, and Ed.</p>
  </WritingArticle>
);
