import React from 'react';

import WritingArticle from '../../components/WritingArticle';

export default () => (
  <WritingArticle
    title="Dish & The Hackathon"
    subtitle="A Brief Study of a Meteor App Getting Built"
    slug="dish-hackathon"
    date="10th June 2015">
    <p>So I recently participated at a Hackathon at the University of Exeter. We had a couple of days to build an app, and come up with a business plan and pitch to market it with. I’d had an idea for an app to take photos of, share, and comment on food at whatever restaurant you’re eating at. I’d have loved to build it as an iOS app protoype, but I didn’t have the time or expertise. Instead I built a responsive app with Meteor.</p>
    <p>Dish is a service that allows you to share pictures of your food along with rating and comments. Conversely, it’s an app that allows to preview the food at the restaurant you’re thinking of heading to by tapping into and indexing a crowd-sourced database of pictures of restaurant food. I developed the product for a hackathon. I still have high hopes for it one day when I get the time to give it the attention it deserves.</p>
    <p>Food related services so often fall back on using gross greens and browns in their palette just because, you know, nature and stuff. However, what people seem to forget is that food, when it’s any good, is bursting with all kinds of colours. With that in mind, we went broad with our colour palette for dish. The deep blue as a main colour is pretty opinionated, especially with that accent pink, but that’s how we liked it. If we iterated this palette further down the line, maybe we’d slightly tone it down - but when you’re trying to stand out at a hackathon, bold is beautiful.</p>
    <img src="http://jackwreid.uk/writing/dish-hackathon/photos/card.png" alt="dish. post" />
    <p>The basic unit of a platform like dish is a post, of course. Posts on dish are represented in a  couple of ways. The most visible of those ways is through the stream where the user logged in lands straight off when landing on the site. In the stream, posts are presented as cards, after all what isn’t these days? Dominating the card, of course, is the picture of the food in question. After that the next most important pieces of information pertain to how to get this food in and around your mouth. So that’s the name of the dish on the restaurant’s menu, and the restaurants where you can actually buy the food, they’re next in the visual hierarchy. The social aspect is key in dish., but when you’re looking at a dish card in your stream, the social dimension is actually fairly irrelevant. People are important because dish. is crowd-sourced food pictures, and the discussion around those pictures, but I never want to overplay social interaction where it’s not wanted - there’s nothing I hate more in a service. For that reason, the user profile picture and username on the dish card are actually pretty small.</p>
    <img src="http://jackwreid.uk/writing/dish-hackathon/photos/upload.png" alt="dish. post" />
    <p>The stream is a dead simple series of dish cards; the upload feature actually took a little more work. For a while I considered something in a similar vein to a Typeform: a highly linear, guided experience with one by one questions like “Where did you eat this?” in big white letters over a full bleed background. However, time constraints took over during the hackathon and I put together what you see here. There’s a little visual flair to this form still: the fields’ underlines turn pink on focus, for example. However, the general experience is a lot less “designed” than originally intended. Part of me think the user experience didn’t really suffer for this compromise - the form is a pretty familiar sight for most users.</p>
    <p>We kept it pretty fast and simple when it came to iconography. We made the decision early on to rely on Font Awesome for what was pretty much a prototype. In the example above you can see the knife and fork icon, which to be honest is a bit eccentric in hindsight. However, I can’t fault the range of the icon set. We very quickly had icons on hand for user profile, notifications, likes, and all the rest. In the next example you’ll see the header of the site with those icons in full us. In hindsight, using those icons along was a blow to accessibility, and usability all round. I’m certainly of the opinion that, you should include text tips to navigational elements - especially in something as key as the site header and root site navigation. In the example you can see above, there are already the beginnings of brutally simple grids of food pictures. Where contextual information about the food is less important, and the user is just expected to be browsing purely on the visuals of the food, there are no obstructing visuals. Just pictures of food, glorious food. If the user is grabbed by something they see, then they can dive deeper and bring textual information and visual chrome into the view by opening the post page.</p>
    <img src="http://jackwreid.uk/writing/dish-hackathon/photos/discover.png" alt="dish. post" />
    <p>Here you can see most of dish’s UI elements in play together. This is the discover page. Like before, we’re using an utterly basic grid of images to let the food take centre stage. The site header is satisfyingly chunky but very minimal in form. The sub navigation is just as minimal, and blends with the site header and root navigation completely, so that it really just feels like an extension of the site header itself rather than a stack of navigation elements on top of one another. Had I had more time, I would have loved to animate the sub navigation to grow out of the site header to reinforce this physicality I had in mind, and really communicate it to the user.</p>
  </WritingArticle>
);
